processed 13 tasks

init:
A: object(0,0)

task 1 'publish'. lines 14-58:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 8474000,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 60-60:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'view-object'. lines 62-62:
Owner: Account Address ( A )
Version: 2
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 4 'run'. lines 64-64:
created: object(4,0), object(4,1), object(4,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'view-object'. lines 66-66:
Owner: Account Address ( A )
Version: 3
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 6 'run'. lines 68-68:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 8664000,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'view-object'. lines 70-70:
Owner: Account Address ( A )
Version: 4
Contents: Test::M1::Parent {id: sui::object::UID {id: sui::object::ID {bytes: fake(2,0)}}, count: 0u64}

task 8 'run'. lines 72-72:
mutated: object(0,0), object(2,0)
deleted: object(4,0), object(4,1), object(4,2)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 8577360, non_refundable_storage_fee: 86640

task 9 'run'. lines 74-74:
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 10 'create-checkpoint'. lines 76-76:
Checkpoint created: 1

task 11 'run-graphql'. lines 78-141:
Response: {
  "data": {
    "latest": {
      "version": 6,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IAPj0IkUMVdLagMPjpKffRVaIJDJK0hqaBfHpcJqKlu0AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IJ3qWm03IM99ZkPlAkGT7kKQ7ep2ZfWghcbOE5Eg8A2GAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "ILnSBS2avY6cZcQREt2cB9gjGW8x8QUdNDUT5aUZyNHmAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df123_removed": {
      "version": 5,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IAPj0IkUMVdLagMPjpKffRVaIJDJK0hqaBfHpcJqKlu0AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IJ3qWm03IM99ZkPlAkGT7kKQ7ep2ZfWghcbOE5Eg8A2GAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "ILnSBS2avY6cZcQREt2cB9gjGW8x8QUdNDUT5aUZyNHmAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    },
    "df456_added": {
      "version": 4,
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IAPj0IkUMVdLagMPjpKffRVaIJDJK0hqaBfHpcJqKlu0AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IAxHSr+I6SQYqgOMdexjwPkTtQ/wcmwItmycfD6edI+EAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMw=="
              },
              "value": {
                "json": "df3"
              }
            }
          },
          {
            "cursor": "IBQAPD1t52wY47n6AnkuyCdGuaMY9hO0SAJszwvahb/wAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMg=="
              },
              "value": {
                "json": "df2"
              }
            }
          },
          {
            "cursor": "IJ3qWm03IM99ZkPlAkGT7kKQ7ep2ZfWghcbOE5Eg8A2GAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "ILnSBS2avY6cZcQREt2cB9gjGW8x8QUdNDUT5aUZyNHmAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          },
          {
            "cursor": "INwA21dGbvkO3kOLY4613pqL17AZ29rrsLW0aswjZFelAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmMQ=="
              },
              "value": {
                "json": "df1"
              }
            }
          }
        ]
      },
      "df1": {
        "name": {
          "bcs": "A2RmMQ=="
        },
        "value": {
          "json": "df1"
        }
      },
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}

task 12 'run-graphql'. lines 143-181:
Response: {
  "data": {
    "latest_owner": {
      "dynamicFields": {
        "edges": [
          {
            "cursor": "IAPj0IkUMVdLagMPjpKffRVaIJDJK0hqaBfHpcJqKlu0AQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNQ=="
              },
              "value": {
                "json": "df5"
              }
            }
          },
          {
            "cursor": "IJ3qWm03IM99ZkPlAkGT7kKQ7ep2ZfWghcbOE5Eg8A2GAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNA=="
              },
              "value": {
                "json": "df4"
              }
            }
          },
          {
            "cursor": "ILnSBS2avY6cZcQREt2cB9gjGW8x8QUdNDUT5aUZyNHmAQAAAAAAAAA=",
            "node": {
              "name": {
                "bcs": "A2RmNg=="
              },
              "value": {
                "json": "df6"
              }
            }
          }
        ]
      },
      "df1": null,
      "df5": {
        "name": {
          "bcs": "A2RmNQ=="
        },
        "value": {
          "json": "df5"
        }
      }
    }
  }
}
