processed 21 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-19:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6315600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 21-21:
Checkpoint created: 1

task 3 'run-graphql'. lines 23-202:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "C5nQLTrG9Pvc9nuccey78qkBUABb1aMdaVsyQFjgKGPZ",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AIuR28kzaE8xaI35xQgMHMtrBWFleolCvIyhM2sDNck4x7RZnecPB3yAxJc/q/ZkNHMnY6W3oHcrQvQL+n0vmw5/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoxfQ",
                  "node": {
                    "__typename": "PublishTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIKBRwRBy0wCF1ACp0BCQymAQ8ABAEGAQcAAAwAAQIEAAIBAgAABQABAAEFAwQAAgoDBwgCAQgAAAEHCAIBCAEDRm9vCVR4Q29udGV4dANVSUQCaWQBbQNuZXcGb2JqZWN0CnR4X2NvbnRleHQCeHMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAICAwgBCAoDAAEAAAIFCwERAQsAEgACAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoxfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 0
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 2,
            "dependencies": {
              "nodes": [
                {
                  "digest": "7kYEwQwTVHZ2Wuf6RyQ3KaJc4CF9iddGGWbQWhbMSu6u"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-7315600",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12",
                    "digest": "DDVu1jJvkyPZ2w4vbxdAuCRy77eZwuK2WUAU7arGYJuy"
                  }
                },
                {
                  "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                    "digest": "96ogNzQcmJosk2g4TrrNZxBew1TRzVxXPCk1MmnxtoLy"
                  }
                },
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                    "digest": "2sPTfGBe9cZL9pmoZimCJRpPE4qJPFaBkygkR3gqYiaV"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6315600",
                "storageRebate": "0",
                "nonRefundableStorageFee": "0"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 1
            },
            "transactionBlock": {
              "digest": "C5nQLTrG9Pvc9nuccey78qkBUABb1aMdaVsyQFjgKGPZ"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 4 'upgrade'. lines 204-222:
created: object(4,0)
mutated: object(0,0), object(1,1)
gas summary: computation_cost: 1000000, storage_cost: 6589200,  storage_rebate: 2595780, non_refundable_storage_fee: 26220

task 5 'create-checkpoint'. lines 224-224:
Checkpoint created: 2

task 6 'run-graphql'. lines 226-405:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "7oGrRPHS4U8cHMMmySxXzT3LPG8644EdibdzmW3WirPM",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AGCuiNpzbiXl20Z/j+UrylMFnzPGlwTmgAveMvqFCYcRaryFudeoO1USAw4UF6uJM6dDLWRbmJ7mB/FYJPtSgAp/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "OwnedOrImmutable",
                    "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                    "version": 2,
                    "digest": "96ogNzQcmJosk2g4TrrNZxBew1TRzVxXPCk1MmnxtoLy",
                    "object": {
                      "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                      "version": 2,
                      "digest": "96ogNzQcmJosk2g4TrrNZxBew1TRzVxXPCk1MmnxtoLy",
                      "asMoveObject": {
                        "contents": {
                          "type": {
                            "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                          },
                          "json": {
                            "id": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                            "package": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12",
                            "version": "1",
                            "policy": 0
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "AA=="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "IKtSxFg0BLyRn8vrtIRqeqpsihVPvPFxPFBg5s0K+UqS"
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "authorize_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "u8"
                        },
                        {
                          "repr": "vector<u8>"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeTicket"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjoyfQ",
                  "node": {
                    "__typename": "UpgradeTransaction",
                    "modules": [
                      "oRzrCwYAAAAIAQAGAgYMAxIUBSYRBzc8CHNACrMBCQy8AR0ABgEIAQkAAAwAAQIEAAIBAgAABwABAAADAQIAAQQEAgABBwMEAAIKAwcIAgEIAAABBwgCAQgBA0ZvbwlUeENvbnRleHQDVUlEBGJ1cm4GZGVsZXRlAmlkAW0DbmV3Bm9iamVjdAp0eF9jb250ZXh0AnhzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgACAgUIAQoKAwABAAACBQsBEQMLABIAAgEBAAACBQsAEwABEQICAA=="
                    ],
                    "dependencies": [
                      "0x0000000000000000000000000000000000000000000000000000000000000001",
                      "0x0000000000000000000000000000000000000000000000000000000000000002"
                    ],
                    "currentPackage": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12",
                    "upgradeTicket": {
                      "__typename": "Result",
                      "cmd": 0,
                      "ix": null
                    }
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjoyfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x0000000000000000000000000000000000000000000000000000000000000002",
                    "module": "package",
                    "functionName": "commit_upgrade",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeCap"
                        },
                        {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::package::UpgradeReceipt"
                        }
                      ],
                      "return": []
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 3,
            "dependencies": {
              "nodes": [
                {
                  "digest": "7kYEwQwTVHZ2Wuf6RyQ3KaJc4CF9iddGGWbQWhbMSu6u"
                },
                {
                  "digest": "C5nQLTrG9Pvc9nuccey78qkBUABb1aMdaVsyQFjgKGPZ"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-4993420",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x6155758298f316b042da0d1d3670759704e1537acd7736b91d02b2e242e5030e",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x6155758298f316b042da0d1d3670759704e1537acd7736b91d02b2e242e5030e",
                    "digest": "3jUW4ZtbdvaympCDojw9H4BFCqadDX2XpMcKyr5txSqt"
                  }
                },
                {
                  "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x7e7f9522d32097c9442b91c9f6dd51cb68c4f194ac945bbc58cabcdc1d9814dc",
                    "digest": "HN5rakp8ws3AFWkQNC7kC6ndZSa7nSc1FGpdEBDcM1vM"
                  }
                },
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                    "digest": "EWDca21x3NafkTbgZtMHsSK4PZcHRU2srXkZbrrWv66f"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "6589200",
                "storageRebate": "2595780",
                "nonRefundableStorageFee": "26220"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 2
            },
            "transactionBlock": {
              "digest": "7oGrRPHS4U8cHMMmySxXzT3LPG8644EdibdzmW3WirPM"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 7 'programmable'. lines 407-410:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2280000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'programmable'. lines 412-421:
created: object(8,0), object(8,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 3328800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'create-checkpoint'. lines 423-423:
Checkpoint created: 3

task 10 'run-graphql'. lines 425-613:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "GzrkogYcZeDrh4VjDkS7gjSoDSziY7ZK4HVqZnkHWgA4",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AOR1rZ9hS4TKSZc37mxXQr3Vgb9Xu2LfqX+8LZiPS860PI5lqemGWGKIkQ7b8rntvYDNcYWSfAvdQn7uOqOi0wV/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KgAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "KwAAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "/MyaQhu7E8GmahqpjwrXUCnt6UhXd5xpFbRPlAaLkh4="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      },
                      {
                        "__typename": "Input",
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjoxLCJjIjozfQ",
                  "node": {
                    "__typename": "MakeMoveVecTransaction",
                    "type": {
                      "repr": "u64"
                    },
                    "elements": []
                  }
                },
                {
                  "cursor": "eyJpIjoyLCJjIjozfQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 2
                      },
                      {
                        "__typename": "Input",
                        "ix": 2
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjozLCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6155758298f316b042da0d1d3670759704e1537acd7736b91d02b2e242e5030e",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 0,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo0LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 3,
                        "ix": null
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo1LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6155758298f316b042da0d1d3670759704e1537acd7736b91d02b2e242e5030e",
                    "module": "m",
                    "functionName": "new",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 1,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "vector<u64>"
                        },
                        {
                          "repr": "&mut 0x0000000000000000000000000000000000000000000000000000000000000002::tx_context::TxContext"
                        }
                      ],
                      "return": [
                        {
                          "repr": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12::m::Foo"
                        }
                      ]
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo2LCJjIjozfQ",
                  "node": {
                    "__typename": "MoveCallTransaction",
                    "package": "0x6155758298f316b042da0d1d3670759704e1537acd7736b91d02b2e242e5030e",
                    "module": "m",
                    "functionName": "burn",
                    "typeArguments": [],
                    "arguments": [
                      {
                        "__typename": "Result",
                        "cmd": 5,
                        "ix": null
                      }
                    ],
                    "function": {
                      "isEntry": false,
                      "typeParameters": [],
                      "parameters": [
                        {
                          "repr": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12::m::Foo"
                        }
                      ],
                      "return": []
                    }
                  }
                },
                {
                  "cursor": "eyJpIjo3LCJjIjozfQ",
                  "node": {
                    "__typename": "MergeCoinsTransaction",
                    "coin": {
                      "__typename": "Result",
                      "cmd": 2,
                      "ix": 0
                    },
                    "coins": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 1
                      }
                    ]
                  }
                },
                {
                  "cursor": "eyJpIjo4LCJjIjozfQ",
                  "node": {
                    "__typename": "TransferObjectsTransaction",
                    "inputs": [
                      {
                        "__typename": "Result",
                        "cmd": 2,
                        "ix": 0
                      }
                    ],
                    "address": {
                      "__typename": "Input",
                      "ix": 3
                    }
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "errors": null,
            "lamportVersion": 5,
            "dependencies": {
              "nodes": [
                {
                  "digest": "2UFRvaVGmaemRWRPusFNTxTXJiiGWX5ygynp91ARNLLt"
                },
                {
                  "digest": "7oGrRPHS4U8cHMMmySxXzT3LPG8644EdibdzmW3WirPM"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-3350680",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0x19b0de0704de331b59df9caf47967f047a243eca2f308685ae3a9c5795104a7f",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0x19b0de0704de331b59df9caf47967f047a243eca2f308685ae3a9c5795104a7f",
                    "digest": "2d7BYh8d7zjWSGsdSofLpVhq8YYDvctS1BS6W4FGS9oE",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x35e1f83d0edc329ba7f9ec81941e62ca4adde8a879cf925de1b4c3d882d11b12::m::Foo"
                        },
                        "json": {
                          "id": "0x19b0de0704de331b59df9caf47967f047a243eca2f308685ae3a9c5795104a7f",
                          "xs": [
                            "42",
                            "43"
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                    "digest": "27vLArKHZMXXoCxCsmFM7gavYwqWL4kUqZzmLM5VHZEY",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                          "balance": {
                            "value": "299999982036420"
                          }
                        }
                      }
                    }
                  }
                },
                {
                  "address": "0xfd63d30f2553a379e3b804c74e9c8d2207c10fec58547f20345f258895856a79",
                  "idCreated": true,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xfd63d30f2553a379e3b804c74e9c8d2207c10fec58547f20345f258895856a79",
                    "digest": "AXpw1zg6XkUg1DavLhs2qfizFmAZcqcboNutH4qdZWsm",
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "json": {
                          "id": "0xfd63d30f2553a379e3b804c74e9c8d2207c10fec58547f20345f258895856a79",
                          "balance": {
                            "value": "2000"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "3328800",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 3
            },
            "transactionBlock": {
              "digest": "GzrkogYcZeDrh4VjDkS7gjSoDSziY7ZK4HVqZnkHWgA4"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 11 'programmable'. lines 615-616:
Error: Transaction Effects Status: Unused result without the drop ability. Command result 0, return value 0
Execution Error: ExecutionError: ExecutionError { inner: ExecutionErrorInner { kind: UnusedValueWithoutDrop { result_idx: 0, secondary_idx: 0 }, source: None, command: None } }

task 12 'create-checkpoint'. lines 618-618:
Checkpoint created: 4

task 13 'run-graphql'. lines 620-799:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "digest": "8mPU3QemNwyHuokrPKYNMaeum3GoEkyeLs9jLQGhgFgB",
          "sender": {
            "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
          },
          "signatures": [
            "AA/6hPiqMVp8cZ3665dZVxKszuVMKDliUumuzQ7+QfKQjjg4fUYe2LHs3tgE3zhyraiTQciUiI0u5LAaTRsidQh/UUY663bYjcm3XmNyULIgxJz1t5Z9vxfB+fp8WUoJKA=="
          ],
          "gasInput": {
            "gasSponsor": {
              "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
            },
            "gasPayment": {
              "nodes": [
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
                }
              ]
            },
            "gasPrice": "1000",
            "gasBudget": "5000000000"
          },
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "inputs": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "Pure",
                    "bytes": "6AMAAAAAAAA="
                  }
                }
              ]
            },
            "transactions": {
              "edges": [
                {
                  "cursor": "eyJpIjowLCJjIjo0fQ",
                  "node": {
                    "__typename": "SplitCoinsTransaction",
                    "coin": {
                      "__typename": "GasCoin"
                    },
                    "amounts": [
                      {
                        "__typename": "Input",
                        "ix": 0
                      }
                    ]
                  }
                }
              ]
            }
          },
          "effects": {
            "status": "FAILURE",
            "errors": "Unused result without the drop ability. Command result 0, return value 0",
            "lamportVersion": 6,
            "dependencies": {
              "nodes": [
                {
                  "digest": "GzrkogYcZeDrh4VjDkS7gjSoDSziY7ZK4HVqZnkHWgA4"
                }
              ]
            },
            "balanceChanges": {
              "nodes": [
                {
                  "owner": {
                    "address": "0xfccc9a421bbb13c1a66a1aa98f0ad75029ede94857779c6915b44f94068b921e"
                  },
                  "amount": "-1009880",
                  "coinType": {
                    "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
                  }
                }
              ]
            },
            "objectChanges": {
              "nodes": [
                {
                  "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                  "idCreated": false,
                  "idDeleted": false,
                  "outputState": {
                    "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d",
                    "digest": "3CSH8nHPvQ4S28Np83L5W7vyH5WsPrSEPekirsqEhRpu"
                  }
                }
              ]
            },
            "gasEffects": {
              "gasObject": {
                "address": "0xaedc899e13ef5594bd101322b5dcd69690a76cdeba12ae03dca0a2d040526f4d"
              },
              "gasSummary": {
                "computationCost": "1000000",
                "storageCost": "988000",
                "storageRebate": "978120",
                "nonRefundableStorageFee": "9880"
              }
            },
            "timestamp": "1970-01-01T00:00:00Z",
            "epoch": {
              "epochId": 0
            },
            "checkpoint": {
              "sequenceNumber": 4
            },
            "transactionBlock": {
              "digest": "8mPU3QemNwyHuokrPKYNMaeum3GoEkyeLs9jLQGhgFgB"
            }
          },
          "expiration": null
        }
      ]
    }
  }
}

task 14 'run-graphql'. lines 801-811:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowfQ",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoxfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 813-823:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjowfQ",
          "node": {
            "kind": {
              "__typename": "GenesisTransaction"
            }
          }
        }
      ]
    }
  }
}

task 16 'run-graphql'. lines 825-835:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoxfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo1fQ",
          "node": {
            "kind": {
              "__typename": "ProgrammableTransactionBlock"
            }
          }
        }
      ]
    }
  }
}

task 17 'run-graphql'. lines 837-844:
Response: {
  "data": {
    "address": {
      "transactionBlocks": {
        "nodes": []
      }
    }
  }
}

task 18 'run-graphql'. lines 846-851:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjoyfQ"
        },
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        }
      ]
    }
  }
}

task 19 'run-graphql'. lines 853-858:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        },
        {
          "cursor": "eyJjIjo0LCJ0Ijo0fQ"
        }
      ]
    }
  }
}

task 20 'run-graphql'. lines 860-870:
Response: {
  "data": {
    "transactionBlocks": {
      "edges": [
        {
          "cursor": "eyJjIjo0LCJ0IjozfQ"
        }
      ]
    }
  }
}
