processed 7 tasks

task 1 'publish'. lines 6-26:
created: object(1,0), object(1,1)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 6862800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 28-29:
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 988000,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'programmable'. lines 31-32:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 4 'programmable'. lines 34-36:
mutated: object(0,0), object(1,0)
gas summary: computation_cost: 1000000, storage_cost: 2272400,  storage_rebate: 2249676, non_refundable_storage_fee: 22724

task 5 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 6 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xc21e8787050f79e893abf5a27705c3d3a87724ea4ce92a5b008e5a608ead59e1",
                  "module": "m",
                  "functionName": "get"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": [
                {
                  "__typename": "SharedObjectRead",
                  "address": "0x6227a5d9132efdffbc4924afcb1665c65873dc6fd49626e2a6c92566148de32e",
                  "version": 2,
                  "digest": "GVMNSd5kDnijhfmB5Lutngw8ZrQLCP7k6n9NcTCvf7sG",
                  "object": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xc21e8787050f79e893abf5a27705c3d3a87724ea4ce92a5b008e5a608ead59e1::m::Foo"
                        },
                        "json": {
                          "id": "0x6227a5d9132efdffbc4924afcb1665c65873dc6fd49626e2a6c92566148de32e",
                          "x": "0"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xc21e8787050f79e893abf5a27705c3d3a87724ea4ce92a5b008e5a608ead59e1",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        },
        {
          "kind": {
            "__typename": "ProgrammableTransactionBlock",
            "transactions": {
              "nodes": [
                {
                  "package": "0xc21e8787050f79e893abf5a27705c3d3a87724ea4ce92a5b008e5a608ead59e1",
                  "module": "m",
                  "functionName": "get"
                },
                {
                  "package": "0xc21e8787050f79e893abf5a27705c3d3a87724ea4ce92a5b008e5a608ead59e1",
                  "module": "m",
                  "functionName": "inc"
                }
              ]
            }
          },
          "effects": {
            "status": "SUCCESS",
            "unchangedSharedObjects": {
              "nodes": []
            }
          }
        }
      ]
    }
  }
}
