processed 17 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 17-38:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5479600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 40-41:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'create-checkpoint'. lines 43-43:
Checkpoint created: 1

task 4 'programmable'. lines 45-48:
created: object(4,0), object(4,1)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 4932400,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 5 'create-checkpoint'. lines 50-50:
Checkpoint created: 2

task 6 'programmable'. lines 52-56:
created: object(6,0), object(6,1), object(6,2)
mutated: object(0,0), object(2,0)
gas summary: computation_cost: 1000000, storage_cost: 6247200,  storage_rebate: 2279772, non_refundable_storage_fee: 23028

task 7 'create-checkpoint'. lines 58-58:
Checkpoint created: 3

task 9 'create-checkpoint'. lines 62-62:
Checkpoint created: 4

task 10 'run-graphql'. lines 64-138:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                "value": "3"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                "value": "5"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                "value": "2"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                "value": "6"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                "value": "4"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                "value": "200"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects_consistent_with_address_at_latest_checkpoint_4": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaf7be07272883d389b95371796917ac75e4653df657f0ae7897b8ee8dbb8ce3a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 11 'run-graphql'. lines 140-184:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "0"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaf7be07272883d389b95371796917ac75e4653df657f0ae7897b8ee8dbb8ce3a",
                        "balance": {
                          "value": "300000000000000"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaf7be07272883d389b95371796917ac75e4653df657f0ae7897b8ee8dbb8ce3a",
                        "balance": {
                          "value": "299999996697200"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaf7be07272883d389b95371796917ac75e4653df657f0ae7897b8ee8dbb8ce3a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}

task 12 'force-object-snapshot-catchup'. lines 186-186:
Objects snapshot updated to [0 to 3)

task 13 'create-checkpoint'. lines 188-188:
Checkpoint created: 5

task 14 'run-graphql'. lines 190-264:
Response: {
  "data": {
    "address_at_latest_checkpoint_4": {
      "objects": {
        "nodes": [
          {
            "contents": {
              "json": {
                "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                "value": "3"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                "value": "5"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                "value": "2"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                "value": "6"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                "value": "4"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          },
          {
            "contents": {
              "json": {
                "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                "value": "200"
              },
              "type": {
                "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
              }
            }
          }
        ]
      }
    },
    "latest_tx_at_checkpoint_3": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            },
            "gasPayment": {
              "nodes": [
                {
                  "asMoveObject": {
                    "contents": {
                      "type": {
                        "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                      },
                      "json": {
                        "id": "0xaf7be07272883d389b95371796917ac75e4653df657f0ae7897b8ee8dbb8ce3a",
                        "balance": {
                          "value": "299999993044572"
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    },
    "object_at_checkpoint_2": {
      "owner": {
        "owner": {
          "objects": {
            "nodes": [
              {
                "contents": {
                  "json": {
                    "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                    "value": "3"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                    "value": "5"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                    "value": "2"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                    "value": "6"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                    "value": "4"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              },
              {
                "contents": {
                  "json": {
                    "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                    "value": "200"
                  },
                  "type": {
                    "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                  }
                }
              }
            ]
          }
        }
      }
    }
  }
}

task 15 'create-checkpoint'. lines 266-266:
Checkpoint created: 6

task 16 'run-graphql'. lines 268-303:
Response: {
  "data": {
    "all_transactions": {
      "nodes": [
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": null
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "100"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        },
        {
          "sender": {
            "objects": {
              "nodes": [
                {
                  "contents": {
                    "json": {
                      "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                      "value": "3"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                      "value": "5"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                      "value": "2"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                      "value": "6"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                      "value": "4"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                },
                {
                  "contents": {
                    "json": {
                      "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                      "value": "200"
                    },
                    "type": {
                      "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                    }
                  }
                }
              ]
            }
          },
          "gasInput": {
            "gasSponsor": {
              "objects": {
                "nodes": [
                  {
                    "contents": {
                      "json": {
                        "id": "0x1818b7d93d03739b651a5531343e0ac8843a7159ed44579a3e2d699802a2eb25",
                        "value": "3"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x3c317825b994f198684eec1e37b60887875626703dde279aa6b42e2cf9e9b704",
                        "value": "5"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x527725cb59cffeb29d970011aecc640f580bda621df6d8caa0c4d57aa1e38ebd",
                        "value": "2"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x775fa33a7ff62dde0964033ce6894308b748a0d27d02208895d4f9c00ea29183",
                        "value": "6"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x78f77ea239c27f92ec51d9c38895586ad2bc885a97587ef53ef4731690ace4c0",
                        "value": "4"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  },
                  {
                    "contents": {
                      "json": {
                        "id": "0x8aa91a5cb2718583843da71e6ebdbd8eb3d1fac29ace4b9ed71aab51d95d712c",
                        "value": "200"
                      },
                      "type": {
                        "repr": "0x315e10cb689e5a5477f052eb98726e05f366bfc7ef9556737ff2453be42d496b::M1::Object"
                      }
                    }
                  }
                ]
              }
            }
          }
        }
      ]
    }
  },
  "errors": [
    {
      "message": "Requested data is outside the available range",
      "locations": [
        {
          "line": 21,
          "column": 11
        }
      ],
      "path": [
        "all_transactions",
        "nodes",
        0,
        "gasInput",
        "gasSponsor",
        "objects"
      ],
      "extensions": {
        "code": "BAD_USER_INPUT"
      }
    }
  ]
}
