processed 16 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 13-30:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'run'. lines 32-32:
created: object(2,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 3 'run'. lines 34-34:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 4 'run'. lines 36-36:
created: object(4,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 5 'run'. lines 38-38:
created: object(5,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 6 'create-checkpoint'. lines 40-40:
Checkpoint created: 1

task 7 'run'. lines 42-42:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'run'. lines 44-44:
created: object(8,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 9 'run'. lines 46-46:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 48-48:
Checkpoint created: 2

task 11 'run'. lines 50-50:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'run'. lines 52-52:
created: object(12,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 13 'create-checkpoint'. lines 54-54:
Checkpoint created: 3

task 14 'run-graphql'. lines 56-80:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "transactionBlocks": {
            "edges": []
          }
        },
        {
          "sequenceNumber": 1,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0IjoyfQ",
                "node": {
                  "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjozfQ",
                "node": {
                  "digest": "9F7q58WEeRmSa74wzvsdAYCEVkLLjppz7aKsZDpnWjLY",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo0fQ",
                "node": {
                  "digest": "H9UfLC2NNtHArjGgJxz97eHTNRAhCCs6F7zY6izPVFm3",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo1fQ",
                "node": {
                  "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 2,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo2fQ",
                "node": {
                  "digest": "H33vafH25cE5e8W4bL22TbeXU4A3kMzc4yGDBefZsm3v",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo3fQ",
                "node": {
                  "digest": "BN9NvuaH49ZU1Pu4cxiec2pfpKsuF3LP7SdBT1dGQoy2",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0Ijo4fQ",
                "node": {
                  "digest": "72XvNkJuEb8aqq8LTJnWseDPrATKwdBG8Lw6i4vpFYCU",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        },
        {
          "sequenceNumber": 3,
          "transactionBlocks": {
            "edges": [
              {
                "cursor": "eyJjIjozLCJ0Ijo5fQ",
                "node": {
                  "digest": "7tsUnoeDgSFnPZCBzJzMWBVZhmVdTLQ9z6fdz3xejxw9",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              },
              {
                "cursor": "eyJjIjozLCJ0IjoxMH0",
                "node": {
                  "digest": "HSeuUhPcFuUJxbXGthjKCTdud7Ep7SoyzC3nxAYmgazY",
                  "sender": {
                    "objects": {
                      "edges": [
                        {
                          "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3AwAAAAAAAAA="
                        }
                      ]
                    }
                  }
                }
              }
            ]
          }
        }
      ]
    }
  }
}

task 15 'run-graphql'. lines 82-99:
Response: {
  "data": {
    "checkpoints": {
      "nodes": [
        {
          "sequenceNumber": 0,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 1,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 2,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        },
        {
          "sequenceNumber": 3,
          "epoch": {
            "epochId": 0,
            "checkpoints": {
              "nodes": [
                {
                  "sequenceNumber": 0
                },
                {
                  "sequenceNumber": 1
                },
                {
                  "sequenceNumber": 2
                },
                {
                  "sequenceNumber": 3
                }
              ]
            }
          }
        }
      ]
    }
  }
}
