processed 4 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-36:
created: object(1,0), object(1,1), object(1,2), object(1,3), object(1,4), object(1,5)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 15663600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 38-38:
Checkpoint created: 1

task 3 'run-graphql'. lines 40-88:
Response: {
  "data": {
    "suiCoins": {
      "edges": [
        {
          "cursor": "IJrGwU1v0mIJStOVyu6vePNZPn00uCMcRyEHc7Zihrm5AQAAAAAAAAA=",
          "node": {
            "coinBalance": "300000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IK7ciZ4T71WUvRATIrXc1paQp2zeuhKuA9ygotBAUm9NAQAAAAAAAAA=",
          "node": {
            "coinBalance": "299999983336400",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        },
        {
          "cursor": "IOUoep+NZ0Mvkm7Ohe8A2/mMWhJgUo39aN2yfr4xFP/EAQAAAAAAAAA=",
          "node": {
            "coinBalance": "30000000000000000",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
              }
            }
          }
        }
      ]
    },
    "fakeCoins": {
      "edges": [
        {
          "cursor": "IDyD5WnKwadEDvedjsMoY9Ow8ymruxwsyPOkQ16x5bvcAQAAAAAAAAA=",
          "node": {
            "coinBalance": "2",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x32fb3ec2fde93336a6516479f08329b27de75f87eced93703aaadca4ca74682c::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "ID/YIa/ljLjBL+9vIkIfMu9nVOX4I0ZhXAiDvbzwwyGyAQAAAAAAAAA=",
          "node": {
            "coinBalance": "1",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x32fb3ec2fde93336a6516479f08329b27de75f87eced93703aaadca4ca74682c::fake::FAKE>"
              }
            }
          }
        },
        {
          "cursor": "IIHk8CWkFxEpTysaxse57lnbbqEXHacQgfmM0Z4Ag8MDAQAAAAAAAAA=",
          "node": {
            "coinBalance": "3",
            "contents": {
              "type": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x32fb3ec2fde93336a6516479f08329b27de75f87eced93703aaadca4ca74682c::fake::FAKE>"
              }
            }
          }
        }
      ]
    },
    "address": {
      "coins": {
        "edges": [
          {
            "cursor": "IK7ciZ4T71WUvRATIrXc1paQp2zeuhKuA9ygotBAUm9NAQAAAAAAAAA=",
            "node": {
              "coinBalance": "299999983336400",
              "contents": {
                "type": {
                  "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                }
              }
            }
          }
        ]
      },
      "allBalances": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9",
            "node": {
              "coinType": {
                "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI"
              },
              "coinObjectCount": 1,
              "totalBalance": "299999983336400"
            }
          },
          {
            "cursor": "eyJ0IjoiMHgzMmZiM2VjMmZkZTkzMzM2YTY1MTY0NzlmMDgzMjliMjdkZTc1Zjg3ZWNlZDkzNzAzYWFhZGNhNGNhNzQ2ODJjOjpmYWtlOjpGQUtFIiwiYyI6MX0",
            "node": {
              "coinType": {
                "repr": "0x32fb3ec2fde93336a6516479f08329b27de75f87eced93703aaadca4ca74682c::fake::FAKE"
              },
              "coinObjectCount": 3,
              "totalBalance": "6"
            }
          }
        ]
      },
      "firstBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAyOjpzdWk6OlNVSSIsImMiOjF9"
          }
        ]
      },
      "lastBalance": {
        "edges": [
          {
            "cursor": "eyJ0IjoiMHgzMmZiM2VjMmZkZTkzMzM2YTY1MTY0NzlmMDgzMjliMjdkZTc1Zjg3ZWNlZDkzNzAzYWFhZGNhNGNhNzQ2ODJjOjpmYWtlOjpGQUtFIiwiYyI6MX0"
          }
        ]
      }
    }
  }
}
