processed 5 tasks

init:
A: object(0,0)

task 1 'publish'. lines 6-42:
created: object(1,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 7622800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'programmable'. lines 44-46:
created: object(2,0)
mutated: object(0,1)
gas summary: computation_cost: 1000000, storage_cost: 2910800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 3 'create-checkpoint'. lines 48-48:
Checkpoint created: 1

task 4 'run-graphql'. lines 50-71:
Response: {
  "data": {
    "transactionBlocks": {
      "nodes": [
        {
          "effects": {
            "objectChanges": {
              "nodes": [
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0xb6a7a5f56f4498fd9c54ccb62ac92143c7db219bc7bf8a1049a2402120876d69::m::Foo"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  91,
                                  3,
                                  132,
                                  28,
                                  170,
                                  127,
                                  229,
                                  206,
                                  94,
                                  181,
                                  65,
                                  3,
                                  14,
                                  252,
                                  16,
                                  69,
                                  60,
                                  250,
                                  250,
                                  68,
                                  56,
                                  217,
                                  63,
                                  42,
                                  55,
                                  162,
                                  235,
                                  152,
                                  15,
                                  84,
                                  144,
                                  133
                                ]
                              }
                            },
                            {
                              "name": "f0",
                              "value": {
                                "ID": [
                                  91,
                                  3,
                                  132,
                                  28,
                                  170,
                                  127,
                                  229,
                                  206,
                                  94,
                                  181,
                                  65,
                                  3,
                                  14,
                                  252,
                                  16,
                                  69,
                                  60,
                                  250,
                                  250,
                                  68,
                                  56,
                                  217,
                                  63,
                                  42,
                                  55,
                                  162,
                                  235,
                                  152,
                                  15,
                                  84,
                                  144,
                                  133
                                ]
                              }
                            },
                            {
                              "name": "f1",
                              "value": {
                                "Bool": true
                              }
                            },
                            {
                              "name": "f2",
                              "value": {
                                "Number": "42"
                              }
                            },
                            {
                              "name": "f3",
                              "value": {
                                "Number": "43"
                              }
                            },
                            {
                              "name": "f4",
                              "value": {
                                "String": "hello"
                              }
                            },
                            {
                              "name": "f5",
                              "value": {
                                "String": "world"
                              }
                            },
                            {
                              "name": "f6",
                              "value": {
                                "Vector": [
                                  {
                                    "Address": [
                                      91,
                                      3,
                                      132,
                                      28,
                                      170,
                                      127,
                                      229,
                                      206,
                                      94,
                                      181,
                                      65,
                                      3,
                                      14,
                                      252,
                                      16,
                                      69,
                                      60,
                                      250,
                                      250,
                                      68,
                                      56,
                                      217,
                                      63,
                                      42,
                                      55,
                                      162,
                                      235,
                                      152,
                                      15,
                                      84,
                                      144,
                                      133
                                    ]
                                  }
                                ]
                              }
                            },
                            {
                              "name": "f7",
                              "value": {
                                "Option": {
                                  "Number": "44"
                                }
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x5b03841caa7fe5ce5eb541030efc10453cfafa4438d93f2a37a2eb980f549085",
                          "f0": "0x5b03841caa7fe5ce5eb541030efc10453cfafa4438d93f2a37a2eb980f549085",
                          "f1": true,
                          "f2": 42,
                          "f3": "43",
                          "f4": "hello",
                          "f5": "world",
                          "f6": [
                            "0x5b03841caa7fe5ce5eb541030efc10453cfafa4438d93f2a37a2eb980f549085"
                          ],
                          "f7": 44
                        }
                      }
                    }
                  }
                },
                {
                  "outputState": {
                    "asMoveObject": {
                      "contents": {
                        "type": {
                          "repr": "0x0000000000000000000000000000000000000000000000000000000000000002::coin::Coin<0x0000000000000000000000000000000000000000000000000000000000000002::sui::SUI>"
                        },
                        "data": {
                          "Struct": [
                            {
                              "name": "id",
                              "value": {
                                "UID": [
                                  154,
                                  198,
                                  193,
                                  77,
                                  111,
                                  210,
                                  98,
                                  9,
                                  74,
                                  211,
                                  149,
                                  202,
                                  238,
                                  175,
                                  120,
                                  243,
                                  89,
                                  62,
                                  125,
                                  52,
                                  184,
                                  35,
                                  28,
                                  71,
                                  33,
                                  7,
                                  115,
                                  182,
                                  98,
                                  134,
                                  185,
                                  185
                                ]
                              }
                            },
                            {
                              "name": "balance",
                              "value": {
                                "Struct": [
                                  {
                                    "name": "value",
                                    "value": {
                                      "Number": "299999988444520"
                                    }
                                  }
                                ]
                              }
                            }
                          ]
                        },
                        "json": {
                          "id": "0x9ac6c14d6fd262094ad395caeeaf78f3593e7d34b8231c47210773b66286b9b9",
                          "balance": {
                            "value": "299999988444520"
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    }
  }
}
