processed 25 tasks

init:
A: object(0,0), B: object(0,1)

task 1 'publish'. lines 12-29:
created: object(1,0)
mutated: object(0,2)
gas summary: computation_cost: 1000000, storage_cost: 5175600,  storage_rebate: 0, non_refundable_storage_fee: 0

task 2 'create-checkpoint'. lines 31-31:
Checkpoint created: 1

task 3 'run'. lines 33-33:
created: object(3,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 0, non_refundable_storage_fee: 0

task 4 'create-checkpoint'. lines 35-35:
Checkpoint created: 2

task 5 'advance-epoch'. lines 37-37:
Epoch advanced: 0

task 6 'run-graphql'. lines 39-55:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 3
    },
    "epoch": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjozLCJ0IjowfQ",
            "node": {
              "digest": "6EJfYhkXD6q3HfzEcWLcguxcxzofvtSLGSMTD9jmRr7q"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoxfQ",
            "node": {
              "digest": "4XRMCdfyY3F6kkAE6ywepcdxVrKsNL6SDe4vHj8iRrPZ"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoyfQ",
            "node": {
              "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjozfQ",
            "node": {
              "digest": "FhwCcKXoG48gNqTMKdwmgYLSayrBn7Vj1a6zYugRsQBY"
            }
          }
        ]
      }
    }
  }
}

task 7 'run'. lines 57-57:
created: object(7,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 8 'create-checkpoint'. lines 59-59:
Checkpoint created: 4

task 9 'run'. lines 61-61:
created: object(9,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 10 'create-checkpoint'. lines 63-63:
Checkpoint created: 5

task 11 'run'. lines 65-65:
created: object(11,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 12 'create-checkpoint'. lines 67-67:
Checkpoint created: 6

task 13 'advance-epoch'. lines 69-69:
Epoch advanced: 1

task 14 'run'. lines 71-71:
created: object(14,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 15 'create-checkpoint'. lines 73-73:
Checkpoint created: 8

task 16 'run'. lines 75-75:
created: object(16,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 17 'create-checkpoint'. lines 77-77:
Checkpoint created: 9

task 18 'run-graphql'. lines 79-118:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 9
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0IjowfQ",
            "node": {
              "digest": "6EJfYhkXD6q3HfzEcWLcguxcxzofvtSLGSMTD9jmRr7q"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjoxfQ",
            "node": {
              "digest": "4XRMCdfyY3F6kkAE6ywepcdxVrKsNL6SDe4vHj8iRrPZ"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjoyfQ",
            "node": {
              "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0IjozfQ",
            "node": {
              "digest": "FhwCcKXoG48gNqTMKdwmgYLSayrBn7Vj1a6zYugRsQBY"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo0fQ",
            "node": {
              "digest": "9F7q58WEeRmSa74wzvsdAYCEVkLLjppz7aKsZDpnWjLY"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo1fQ",
            "node": {
              "digest": "H9UfLC2NNtHArjGgJxz97eHTNRAhCCs6F7zY6izPVFm3"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo2fQ",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo3fQ",
            "node": {
              "digest": "8t8wARusk3Pd2r1X4qUfJfj38r2GFL9NnhGdGDNgsjnp"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo4fQ",
            "node": {
              "digest": "H33vafH25cE5e8W4bL22TbeXU4A3kMzc4yGDBefZsm3v"
            }
          },
          {
            "cursor": "eyJjIjo5LCJ0Ijo5fQ",
            "node": {
              "digest": "BN9NvuaH49ZU1Pu4cxiec2pfpKsuF3LP7SdBT1dGQoy2"
            }
          }
        ]
      }
    }
  }
}

task 19 'run'. lines 120-120:
created: object(19,0)
mutated: object(0,0)
gas summary: computation_cost: 1000000, storage_cost: 2302800,  storage_rebate: 978120, non_refundable_storage_fee: 9880

task 20 'create-checkpoint'. lines 122-122:
Checkpoint created: 10

task 21 'run-graphql'. lines 124-164:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo0LCJ0IjowfQ",
            "node": {
              "digest": "6EJfYhkXD6q3HfzEcWLcguxcxzofvtSLGSMTD9jmRr7q"
            }
          },
          {
            "cursor": "eyJjIjo0LCJ0IjoxfQ",
            "node": {
              "digest": "4XRMCdfyY3F6kkAE6ywepcdxVrKsNL6SDe4vHj8iRrPZ"
            }
          },
          {
            "cursor": "eyJjIjo0LCJ0IjoyfQ",
            "node": {
              "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo4LCJ0Ijo0fQ",
            "node": {
              "digest": "9F7q58WEeRmSa74wzvsdAYCEVkLLjppz7aKsZDpnWjLY"
            }
          },
          {
            "cursor": "eyJjIjo4LCJ0Ijo1fQ",
            "node": {
              "digest": "H9UfLC2NNtHArjGgJxz97eHTNRAhCCs6F7zY6izPVFm3"
            }
          },
          {
            "cursor": "eyJjIjo4LCJ0Ijo2fQ",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoxMCwidCI6OH0",
            "node": {
              "digest": "H33vafH25cE5e8W4bL22TbeXU4A3kMzc4yGDBefZsm3v"
            }
          }
        ]
      }
    }
  }
}

task 22 'run-graphql'. lines 166-206:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjozLCJ0IjoxfQ",
            "node": {
              "digest": "4XRMCdfyY3F6kkAE6ywepcdxVrKsNL6SDe4vHj8iRrPZ"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjoyfQ",
            "node": {
              "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U"
            }
          },
          {
            "cursor": "eyJjIjozLCJ0IjozfQ",
            "node": {
              "digest": "FhwCcKXoG48gNqTMKdwmgYLSayrBn7Vj1a6zYugRsQBY"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo3LCJ0Ijo1fQ",
            "node": {
              "digest": "H9UfLC2NNtHArjGgJxz97eHTNRAhCCs6F7zY6izPVFm3"
            }
          },
          {
            "cursor": "eyJjIjo3LCJ0Ijo2fQ",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM"
            }
          },
          {
            "cursor": "eyJjIjo3LCJ0Ijo3fQ",
            "node": {
              "digest": "8t8wARusk3Pd2r1X4qUfJfj38r2GFL9NnhGdGDNgsjnp"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo5LCJ0Ijo5fQ",
            "node": {
              "digest": "BN9NvuaH49ZU1Pu4cxiec2pfpKsuF3LP7SdBT1dGQoy2"
            }
          }
        ]
      }
    }
  }
}

task 23 'run-graphql'. lines 208-248:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "epoch_0": {
      "epochId": 0,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoyLCJ0IjoyfQ",
            "node": {
              "digest": "GbMrSH852vRYaBkCopyE3gxfeSeWh6Lv3CBzJSQ4Zs9U"
            }
          }
        ]
      }
    },
    "epoch_1": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo2LCJ0Ijo2fQ",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM"
            }
          }
        ]
      }
    },
    "epoch_2": {
      "epochId": 2,
      "transactionBlocks": {
        "edges": []
      }
    }
  }
}

task 24 'run-graphql'. lines 250-294:
Response: {
  "data": {
    "checkpoint": {
      "sequenceNumber": 10
    },
    "with_cursor": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjo2LCJ0Ijo2fQ",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "IEB4IjGCseRplZyPibCp8DQpx4pPGTZQtZ2I5KJFX0lXBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IFBQHgW9XcAxT1AidwPmuT7kIEAF5y/BmTXZ8HurAL1eBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IF7hhzfaS8K9cQSJ6jE1pCPPW64oFLmZSZKi254GMcubBgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK974HJyiD04m5U3F5aResdeRlPfZX8K54l7jujbuM46BgAAAAAAAAA="
                    },
                    {
                      "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3BgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    },
    "without_cursor": {
      "epochId": 1,
      "transactionBlocks": {
        "edges": [
          {
            "cursor": "eyJjIjoxMCwidCI6NH0",
            "node": {
              "digest": "9F7q58WEeRmSa74wzvsdAYCEVkLLjppz7aKsZDpnWjLY",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "IBXGnu4ZcCEj7YFOt3YmE5XQzuGYhrlhlkBqn8eQMCHtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDDm4G5t0a6lBso0H8LxPA+v4UmNyHG5Hbgx7CdsQXxtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IEB4IjGCseRplZyPibCp8DQpx4pPGTZQtZ2I5KJFX0lXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IFBQHgW9XcAxT1AidwPmuT7kIEAF5y/BmTXZ8HurAL1eCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IF7hhzfaS8K9cQSJ6jE1pCPPW64oFLmZSZKi254GMcubCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK7q+Db7apQNa3f+LBabXQhCSc0g/+eNdT7lLvMWA/TXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK974HJyiD04m5U3F5aResdeRlPfZX8K54l7jujbuM46CgAAAAAAAAA="
                    },
                    {
                      "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3CgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          },
          {
            "cursor": "eyJjIjoxMCwidCI6NX0",
            "node": {
              "digest": "H9UfLC2NNtHArjGgJxz97eHTNRAhCCs6F7zY6izPVFm3",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "IBXGnu4ZcCEj7YFOt3YmE5XQzuGYhrlhlkBqn8eQMCHtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDDm4G5t0a6lBso0H8LxPA+v4UmNyHG5Hbgx7CdsQXxtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IEB4IjGCseRplZyPibCp8DQpx4pPGTZQtZ2I5KJFX0lXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IFBQHgW9XcAxT1AidwPmuT7kIEAF5y/BmTXZ8HurAL1eCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IF7hhzfaS8K9cQSJ6jE1pCPPW64oFLmZSZKi254GMcubCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK7q+Db7apQNa3f+LBabXQhCSc0g/+eNdT7lLvMWA/TXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK974HJyiD04m5U3F5aResdeRlPfZX8K54l7jujbuM46CgAAAAAAAAA="
                    },
                    {
                      "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3CgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          },
          {
            "cursor": "eyJjIjoxMCwidCI6Nn0",
            "node": {
              "digest": "VHRviCLrA6SpQzkvwcDMmRS5Rd4uwyqanKkJc5emWnM",
              "sender": {
                "objects": {
                  "edges": [
                    {
                      "cursor": "IBXGnu4ZcCEj7YFOt3YmE5XQzuGYhrlhlkBqn8eQMCHtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IDDm4G5t0a6lBso0H8LxPA+v4UmNyHG5Hbgx7CdsQXxtCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IEB4IjGCseRplZyPibCp8DQpx4pPGTZQtZ2I5KJFX0lXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IFBQHgW9XcAxT1AidwPmuT7kIEAF5y/BmTXZ8HurAL1eCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IF7hhzfaS8K9cQSJ6jE1pCPPW64oFLmZSZKi254GMcubCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK7q+Db7apQNa3f+LBabXQhCSc0g/+eNdT7lLvMWA/TXCgAAAAAAAAA="
                    },
                    {
                      "cursor": "IK974HJyiD04m5U3F5aResdeRlPfZX8K54l7jujbuM46CgAAAAAAAAA="
                    },
                    {
                      "cursor": "ILijIptEB9Bd22/k6bSwkdkc6dV6C5DhlpRj3IDhPOa3CgAAAAAAAAA="
                    }
                  ]
                }
              }
            }
          }
        ]
      }
    }
  }
}
